Add copy button to document pages
ApplicantAtlas/ApplicantAtlas pull request #148
Opened 2024-08-04 18:02 UTC by vietluong2110

2024-08-04 20:19 UTC, davidteather commented
looks like the clipmark gets a little odd on small screens
<img width="178" alt="image" src="https://github.com/user-attachments/assets/3b8e1144-8aa9-4187-8310-f9ce1b28c9f7">


here's the css styles I used on my personal site, which might help
```css

.prose pre code {
    display: block; 
    white-space: pre-wrap;
    word-break: break-word;
    padding: 0;
    background-color: inherit;
    border-radius: inherit;
    color: #adbac7;
}


span[data-rehype-pretty-code-title] + pre {
    margin-top: -0.2rem;
    border-top-left-radius: 0;
}

span[data-rehype-pretty-code-title] {
    background-color: #22272e;
    color: #adbac7;
    padding: 4px;
    padding-left: 8px;
    padding-right: 8px;
    border-radius: 4px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
    font-size: 0.8rem;
}

.highlighted {
    background-color: #57c7f933;
}
code {
    background-color: #22272e !important;
    color: #adbac7 !important;
    font-size: 0.9rem !important;
}
```

and had this rehype plugin since I was running into issues with <figure>
```tsx

function rehypeReplaceFigureAndCaption() {
    return (tree) => {
        visit(tree, 'element', (node, index, parent) => {
            // Change <figure> to <div> if it has the specific data attribute
            if (node.tagName === 'figure' && node.properties && node.properties['data-rehype-pretty-code-figure'] !== undefined) {
                node.tagName = 'div';  // Change the tag name to <div>
            }
            // Change <figcaption> to <span>
            if (node.tagName === 'figcaption' && node.properties && node.properties['data-rehype-pretty-code-title'] !== undefined) {
                node.tagName = 'span';
            }
        });
    };
}
```

and for extra functionality allowing highlighting of nodes
```js
[rehypePrettyCode, {
            transformers: [
                transformerCopyButton({
                    visibility: 'always',
                    feedbackDuration: 500,
                }),
            ],
            onVisitLine(node) {
                // Prevent lines from collapsing in `display: grid` mode, and
                // allow empty lines to be copy/pasted
                if (node.children.length === 0) {
                    node.children = [{ type: 'text', value: ' ' }];
                }
            },
            onVisitHighlightedLine(node) {
                if (!node.properties.className) {
                    node.properties.className = [];
                }
                node.properties.className.push('highlighted');
            },
        }]
```

would be nice to support like

> \`\`\`js title="mypagename.tsx"
the above code should be able to do this along with highlughting specific lines within the block as it does in my portfolio website like
> \`\`\`astro title="components/AstroSearch.astro" {48-53, 57, 63-70}

2024-08-04 20:21 UTC, davidteather requested changes

2024-08-04 20:21 UTC, davidteather commented on package-lock.json
> +{
delete this file, no npm on the root level only within `website`

2024-08-04 20:21 UTC, davidteather commented on website/lib/markdown.ts
> +          feedbackDuration: 3_000,
drop to `500` for feedback duration

2024-08-05 22:34 UTC, vietluong2110 commented
@davidteather  I adjusted the position of the copy button. Thank you for your css code snippet!

2024-08-10 18:15 UTC, davidteather requested changes
* why json in `gitignore`

otherwise looks look, there's some overflow with single tick code blocks but I'll try to deal with that later

2024-08-10 18:15 UTC, davidteather commented on .gitignore
> +*.json
why adding `*.json`?

2024-08-27 00:38 UTC, davidteather approved these changes

2024-08-27 00:57 UTC, merged